### ISSUE TITLE
[NPU메모리 시스템]

### ISSUE THREAD

**Issue by kingdori1** [casys-kaist/mNPUsim#1]
안녕하세요~!! 좋은 코드 공유해주셔서 감사합니다. 저는 가상화에 관심히 많은 전자과 3학년 학생입니다. 얕은 지식이지만,  혹시 NPU 메모리 쪽 가상화를 할 때 메모리 사용 정보를 가져올 때 hypervisor로부터 가져오는 것이 아닌가요? 각 VM의 vNPU 메모리 사용 정보는 어떻게 가져올까요? 감사합니다!

**Comment by terrafin** [comment]
안녕하세요. 현재 mNPUsim에서는 일반적인 가상 메모리 기술을 NPU 메모리 주소 공간에 적용한 상황을 모델링하고 있으며, 말씀하신 것과 같이 가상화된 NPU에 대한 완전한 지원은 아직 이루어지지 않고 있습니다. 시스템 가상화와 가상 메모리가 모두 'virtualization'이라는 용어를 사용하기 때문에 다소 혼동이 생길 수 있을 것 같은데, 차후 설명을 보강하도록 하겠습니다. 감사합니다.
