### ISSUE TITLE
Multicore로의 computation 분배

### ISSUE THREAD

**Issue by yerjin** [casys-kaist/mNPUsim#2]
안녕하세요. 혹시 NPU core가 여러 개인 상황에서 연산을 분배할 때, 하나의 layer를 tiling 해서
나온 연산들을 각 core에 분배하고, 그것을 다시 합쳐주는 식으로 동작하는지 의문이 생겨 issue 남깁니다.
감사합니다.

**Comment by terrafin** [comment]
안녕하세요. 현재 mNPUsim은 말씀하신 것과 같은 단일 워크로드의 멀티코어 프로세싱을 지원하지 않으며, NPU 코어의 수와 워크로드 (DNN 모델) 수가 같은 경우만을 가정하고 있습니다. 즉, N개의 워크로드를 N개의 NPU 코어에서 실행시키며, 각 워크로드가 하나의 코어의 연산 유닛 및 SPM을 독점하는 시나리오입니다.
